name: webkit_inspection_protocol
version: 0.8.0-nullsafety.0
description: A client for the Chrome DevTools Protocol (previously called the Webkit Inspection Protocol).
homepage: https://github.com/google/webkit_inspection_protocol.dart

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  logging: ^1.0.0-nullsafety.0

dev_dependencies:
  args: ^2.0.0-nullsafety
  # shelf: ^0.7.0
  # shelf_static: ^0.2.0
  # shelf_web_socket: ^0.2.0
  # test: ^1.16.0-nullsafety.12
  # webdriver: ^2.0.0

dependency_overrides:
  args:
    git:
      url: git://github.com/dart-lang/args.git
      ref: master
